### ISSUE TITLE
Write a little IoC container

### ISSUE THREAD

**Issue by alexyork** [Smeedee/Smeedee-Mobile#10]
At the moment, we have a static ISmeedeeService instance which we can override with real or fake implementations.  This works well so far, as Lars has already pointed out.

The problem will arise when we have more and more services we wish to fake.  e.g. a KeyValue storage service, an ErrorReporter service, etc etc.

I think we should have a class called ServiceLocator which takes care of all of the dependencies.

When the app starts, we will do this:
 var serviceLocator = SmeedeeApp.ServiceLocator;
serviceLocator.Bind<ISmeedeeService>().To(new HttpSmeedeeService());
serviceLocator.Bind<IKeyValueStorage>().To(new AndroidStorageService());

in the model objects we can pull the services out, like this:
var httpService = serviceLocator.Get<ISmeedeeService>();

You dig?

**Comment by dagolap** [comment]
Me and Lars M. pair programmed this now. It's very simple. Do you want any more features?

**Comment by alexyork** [comment]
No, it looks perfect. It is so small and simple - that is exactly what we want. Now we just start using it in the production code and in the tests. Great work!

**Comment by dagolap** [comment]
Great! :) I'm closing this ticket then. 

Also, we started using the container for the SmeedeeService that was previously available from SmeedeeApp, and all usages in the android-, shared- and test projects are now reflecting this. Hope we haven't wrecked to much havoc on the iPhone project :)
