### ISSUE TITLE
Position of the Next/Prev buttons in Android app

### ISSUE THREAD

**Issue by alexyork** [Smeedee/Smeedee-Mobile#11]
As a user, I would expect the Previous button to be on the top left of the app, and the Next button to be on the top right.

**Comment by rodsjo** [comment]
I agree with you, but the buttons are there just now for navigation purposes, and will be removed when we fix the swiping views to left and right with finger gestures.

**Comment by alexyork** [comment]
Good point Børge!

Don't fix this issue right now - and maybe close it later on when swiping is finished :-)
