### ISSUE TITLE
Remove logo in the title bar (Android)

### ISSUE THREAD

**Issue by alexyork** [Smeedee/Smeedee-Mobile#12]
Having the logo in the title bar is great - but we lose too much screen real estate.

How about removing it, but instead, having a faded/pale version of the icon as the background in the title-bar (centered).  This way, we still have the image visible, but we don't lose any screen real-estate - meaning we get more room for the widget title.

**Comment by rodsjo** [comment]
First, we thought that we should have a logo for each smeedee widget that was displayed in the top left corner, and the widget title following to the right. That was why the smeedee logo was shown in the upper left, it was supposed to be removed with different widget logos.

Now, someone think that we should not care about widget icons, and just have a title and description. We should have a meeting about the issue today!

Thanks for your thoughts, will take them in consideration

**Comment by alexyork** [comment]
Great! Sounds like this is well under control then. 

Wen you have made a decision, document it here and then close this issue :-)

Seems like you are one step ahead of me! That's great!
