### ISSUE TITLE
Normalize fonts and colors

### ISSUE THREAD

**Issue by dagolap** [Smeedee/Smeedee-Mobile#13]
Normalize font size and colors everywhere.

I've started by adding a Colors.xml file to the resources so we can use resource id's to fetch colors.

We should also agree on and implement standards for font sizes etc so everything looks coherent.

**Comment by rodsjo** [comment]
I totally agree. Does the Colors.xml work? I tried to do that as well, but Android could not find the attributes and values I stated there.

Anyway; this issue will be fixed when we make an overall theme theme for the whole application. Think this could be done in Sprint 3 when polishing the UI. Or of course next week if someone finds time
